### ISSUE TITLE
Controller tests throw errors in MiniTest

### ISSUE THREAD

**Issue by HuckyDucky** [halogenandtoast/monban#41]
While I can click through my Monban-authenticated views just fine, my controller tests continue to fail. And the errors 100% of the time have to do with *warden* not being part of the request.

Here is a very simple test:

```
require 'test_helper'

describe CatalogsController do
  describe "#create" do
    
    # I have no idea how to run the reset *after* in MiniTest, so hopefully this does it.
    before do
      Monban.test_reset!
    end
    
    it do "valid"
      user = FactoryGirl.create(:user, :organization_admin_role)
      sign_in(user)
      post :create, { catalog: { name: "My Catalog", description: "Description of my catalog."}}
      assert_redirected_to catalog_path(Catalog.last)
    end
    
    it do "invalid"
      user = FactoryGirl.create(:user, :organization_admin_role)
      sign_in(user)
      post :create, { catalog: { name: "" }}
      assert_select ".error"
    end

  end
end
```

Inside my *test_helper.rb*:

```
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
require "rails/test_help"
require "minitest/rails"
require "minitest/reporters"
require 'monban/test/helpers'

Minitest::Reporters.use!

# Override password hashing
Monban.test_mode!

Dir[Rails.root.join("test/support/*.rb")].each do |f|
  require f
end

# To add Capybara feature tests add `gem "minitest-rails-capybara"`
# to the test group in the Gemfile and uncomment the following:
require "minitest/rails/capybara"
require 'capybara-screenshot/minitest'

# Uncomment for awesome colorful output
# require "minitest/pride"

include LoginMacros
include Monban::Test::Helpers
include Monban::Test::ControllerHelpers

def main_app
  Rails.application.class.routes.url_helpers
end

class ActiveSupport::TestCase
  include Capybara::DSL
  ActiveRecord::Migration.check_pending!

    # Setup all fixtures in test/fixtures/*.(yml|csv) for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

The error is being thrown off of the *post* lines in the test:

```
NoMethodError:         NoMethodError: undefined method `set_user' for nil:NilClass
            /Users/me/myapp/.gems/ruby/2.2.0/gems/monban-0.2.0/lib/monban/services/sign_in.rb:17:in `perform'
            /Users/me/myapp/.gems/ruby/2.2.0/gems/monban-0.2.0/lib/monban/controller_helpers.rb:21:in `sign_in'
            /Users/me/myapp/.gems/ruby/2.2.0/gems/monban-0.2.0/lib/monban/test/controller_helpers.rb:18:in `sign_in'
            /Users/me/myapp/test/controllers/catalogs_controller_test.rb:13:in `block (3 levels) in <top (required)>'
```

The *Monban* code:

      # Perform the service
      def perform
        @warden.set_user(@user)
      end

I've had some other errors as well. Always related to *warden* not being set in the test session. I have never had such problems before. I am certain there must be a setup issue that I'm missing, but if I can't find it after 4 hours, then I'm not sure what step to take next.

**Comment by HuckyDucky** [comment]
I've jumped through the hoop. I should have had this in my *test_helper.rb*:
```
class ActionController::TestCase
  include Monban::Test::Helpers
  include Monban::Test::ControllerHelpers
end
```

rather than just put the includes by themselves in there. Test passes now. I imagine that the tests were calling the actual Monban helpers rather than the Monban test helpers before. And I guess that the warden middleware must not get invoked in the same fashion for controller tests as it does when the code is accessed via the browser.

**Comment by halogenandtoast** [comment]
Glad you figured this out. I've only really tested this against RSpec so if this works out for you I (or you) can document using it with MiniTest.

**Comment by HuckyDucky** [comment]
OK. I am keeping copious notes as I go through this, happy to add them to docs.

**Comment by halogenandtoast** [comment]
Awesome! Glad to hear it!

**Comment by HuckyDucky** [comment]
Ugh. I'm on day 3 of trying to get an integration test to run in Minitest. I can't get the session to behave properly.

I have a login helper method that doubles as kind of an integration test against security:
```
module LoginMacros

  def login_user(type = 'User')

    if type=="Admin"
      user = FactoryGirl.create(:user, :admin)
    elsif type=="Organization Admin"
      user = FactoryGirl.create(:user, :organization_admin_role)
    elsif type=="Organization User"
      user = FactoryGirl.create(:user, :organization_user_role)
    else
      user = FactoryGirl.create(:user)
    end
    visit new_session_path
    fill_in 'Email', :with => user.email
    fill_in 'Password', :with => user.password_digest
    click_button 'Log in'
    user
  end

  def login_organization_admin_user
    login_user('Organization Admin')
  end

  def login_organization_user
    login_user('Organization User')
  end

  def login_admin_user
    login_user('Admin')
  end

end
```

In my *sessions* controller I add a couple of values into the session after authenticating the user and doing the sign_in:
```
  def create
    
    user = authenticate_session(session_params)

    if sign_in(user)
      if user.admin?
        redirect_to system_admin_index_path
      else
        session[:organization_id] = user.default_organization_id
        default_catalog = user.default_catalog(user.default_organization_id)
        session[:catalog_id] = default_catalog.id if default_catalog
        redirect_to home_index_path
      end
    else
      flash.now[:error] = "Your username/password combination is not valid. Please try again."
      render :new
    end
  end
```

The reason I have to call this login macro instead of just doing a simple ```sign_in(user)``` is that I need to set a couple of session variables that determine what the user sees on his screen, and where he's redirected to after login.

My problem is:

* If I use the login code, even though ```sign_in``` is called there, *none of the helpers work*, ie ```current_user``` is nil after sign_in. The valid user object is indeed returned from ```sign_in```, but ```current_user``` returns nil. So that just doesn't work.

* However, if I put the call to ```sign_in``` directly into the test itself, the helpers *do* work. But now I'm in the situation that my tests fail because I have been unable to set those session variables. 

I'm screwed either way. I have to either:

    a) figure out why the ```sign_in``` message acts differently in the controller than in the login test helper

    or 

    b) figure out how to set session variables from the test helper

in order to get past this. I'll put about 4 more hours into it.

**Comment by HuckyDucky** [comment]
Bingo! So stupidly easy as to have taken about 6 hours.

Trying to do too much with a controller test. Indeed, the test was called ```sign_in``` from ```Monban::Test::ControllerHelpers```, but of course the namespace the controller referred to was ```Monban::ControllerHelpers``` as the include in ```ApplicationController``` specifies.

The best answer was to not use the login helper at all for the controller test, and instead move some of that ```SessionsController#create``` code into the test itself:

```
    it do "valid"
      user = FactoryGirl.create(:user, :organization_admin_role)
      sign_in(user)
      session[:organization_id] = user.default_organization_id
      default_catalog = user.default_catalog(user.default_organization_id)
      session[:catalog_id] = default_catalog.id if default_catalog
      post :create, { catalog: { name: "My Catalog", description: "Description of my catalog."}}
      assert_redirected_to catalog_path(Catalog.last)
    end
```
So setting the session variables in a controller test is as simple as it is to set them in a controller.
