### ISSUE TITLE
Notices should use I18n

### ISSUE THREAD

**Issue by halogenandtoast** [halogenandtoast/monban#43]

**Comment by halogenandtoast** [comment]
Originally I thought this, but there's only one notice here and it's configurable so I don't think this is necessary anymore.

**Comment by shishi** [comment]
I need I18n for notice. For now, I do like this

```ruby
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :set_notice
  before_action :require_login

  def set_notice
    if params[:lang] == 'en'
      Monban.config.sign_in_notice = 'hugahugahuga'
    elsif params[:lang] == 'ja'
      Monban.config.sign_in_notice = 'ja'
    end
  end
end
```

It works, but I think this is not good idea. Do you have other idea?

**Comment by halogenandtoast** [comment]
@shishi I just pushed a release that makes this a bit easier. Check the documentation here:

https://github.com/halogenandtoast/monban#using-i18n-for-sign-in-notice

**Comment by halogenandtoast** [comment]
@shishi please upgrade to 1.1.0

**Comment by shishi** [comment]
Thanks! I will try

**Comment by shishi** [comment]
It works perfectly!

**Comment by halogenandtoast** [comment]
嬉しい
