### ISSUE TITLE
ActionController::Params.to_hash is deprecated and will be removed in rails 5.1

### ISSUE THREAD

**Issue by halogenandtoast** [halogenandtoast/monban#44]
https://github.com/halogenandtoast/monban/blob/master/lib/monban/services/sign_up.rb#L19

**Comment by halogenandtoast** [comment]
Should just need to change to `to_h`

**Comment by derekprior** [comment]
This would break out of the mass assignment security provided by
ActionController::Params. What's the reason to call `to_hash` there in the
first place?

**Comment by halogenandtoast** [comment]
@derekprior The original reason was to get the additional values (like username) that Monban doesn't know about, `to_h` doesn't break out of mass assignment security in rails 5. See http://edgeapi.rubyonrails.org/classes/ActionController/Parameters.html#method-i-to_h

**Comment by halogenandtoast** [comment]
This is the case for rails 4 as well so I'm going to issue this fix immediately.

**Comment by halogenandtoast** [comment]
@derekprior care to look at #45
