### ISSUE TITLE
lookup additional fields 

### ISSUE THREAD

**Issue by shishi** [halogenandtoast/monban#52]
In Readme, I found Monban can lookup multiple field (email or username). But I want to add required field for user lookup.
For example,  User class has username, additional_field and password. username and additional_field are composite unique.

I found `FieldMap` class and I think I need to overwrite `query_string` or `authenticate_session`. Do you have any good idea?

**Comment by halogenandtoast** [comment]
What do you mean by "username and additional_field are composite unique" and how does this affect lookup?

**Comment by shishi** [comment]
I mean I want username is not unique, so I need additional filed for finding user.

**Comment by halogenandtoast** [comment]
@shishi just for clarification have you tried just calling `authenticate_session(session_params)` with both fields. I don't see anything in the code that would prevent this from working.

**Comment by halogenandtoast** [comment]
@shishi, where session params is in the format:

```ruby
{
  password: "foo",
  username: "bar",
  additional_field: "baz"
}
```

**Comment by halogenandtoast** [comment]
You should probably also configure the user_lookup_field to be `id` instead of `email`:

```ruby
config.user_lookup_field = :id
```

This is used by Warden

**Comment by shishi** [comment]
I totally make an unwarranted assumption about Monban lookup user with single field.
I re-read FieldMap, `params_with_symbolized_keys` generate hash with passed all field without token...
I am so sorry worthless issue.
